app:
    resource: '@AppBundle/Controller/'
    type: annotation

movies:
    type: rest
    resource: AppBundle\Controller\MoviesController

movies_post:
    path: /movies
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\MoviesController:postMoviesAction
        _format: json

movies_patch:
    path: /movies/{movie}
    methods: [PATCH]
    defaults:
        _controller: AppBundle\Controller\MoviesController:patchMovieAction
        _format: json

humans:
    type: rest
    resource: AppBundle\Controller\HumansController

humans_post:
    path: /humans
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\HumansController:postHumansAction
        _format: json

movies_roles_post:
    path: /movies/{movie}/roles
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\MoviesController:postMovieRolesAction
        _format: json

user:
    resource: AppBundle\Controller\UsersController
    type: annotation

users_post:
    path: /users
    methods: [POST]
    defaults:
        _controller: AppBundle\Controller\UsersController:postUserAction
        _format: json

tokens:
    resource: AppBundle\Controller\TokensController
    type: rest
